# Blog settings
permalink: :title


# My variables
name: React.js 小書
description: React.js 小書是一個開源、免費、專業、簡單的 React.js 線上教程
site_root: /books/react
static_path: https://huzidaha.github.io/static
# static_path: /books/react/
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: none

gems:
  - jekyll-sitemap
